---
title: "Introduction to Rmarkdown Exercise"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This repository holds materials for the first course assignment.
We simply want you to introduce yourselves and your research interests to us,
while at the same time learning how to write things using Rmarkdown and then
knitting that document to different formats.

The file `about-me.Rmd` provides a skeleton to follow.  You should just
edit that file, modifying it to include your own information in it.  There are certain goals
in each section (like using numbered lists, or writing code in fenced code blocks) as listed
in each section.  

The file `about-me-example.Rmd` gives some information about Eric, and shows an example of what your response could look like.
You can study it to learn about Rmarkdown syntax.  We have included three different RMarkdown outputs of that
file to see what they look like:

1. about-me-example.html
1. about-me-example.pdf
1. about-me-example.docx

To learn more about RMarkdown, as part of this assigment, you are also expected to
download RStudio's [RMarkdown Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf)
and study it carefully.  If you are completely new to RMarkdown, some of it might be mysterious,
but keep coming back to these sorts of RStudio cheat sheets.  I learn something new every time I read them.

Try knitting your document to all three formats found in the YAML header (HTML, PDF, Word).  Note that
to get the PDF version done right, you probably have to add an image which is
your original JPG, but converted to a PDF.  (i.e. like `images/eric.pdf`).  This can be done

**Super Bonus Points:** If you really want to impress us, try adding a few things that we
have suggested in the template to your own document. You can find lots of things you might
try in the RMarkdown cheat sheet. For example:

- Make a markdown table of something,
- Play with different text formatting,
- Try also rendering your document to a Slidy presentation. (But note that you may wish to rename the document so
doing this does not overwrite your plain old `about-me.html` file.)

**Turning in your assignment**

Once you are done. Commit all your changes (feel free to make intermediate commits as well)
and any new files, and push those back to GitHub.  You should commit, at a minimum,  `about-me.Rmd` and
`about-me.html`, `about-me.pdf`, and `about-me.docx`.

That constitutes turning the assignment in.




